### ISSUE TITLE
Developing Gdip2: Webpack not on path

### ISSUE THREAD

**Issue by hoppfrosch** [tariqporter/Gdip2#1]
Within your Readme.md you wrote:

> Install npm dependencies
> npm install
> and then run webpack to build to dist folder
> webpack -w

NPM install works fine - but webpack is not available after this: it's installed, but the command webpack cannot be found. Probably the path is not set correctly. 
What's to be done to be able to run webpack?

**Comment by tariqporter** [comment]
I had webpack globally installed. Follow instructions now to run it locally, and watch all files for changes - causing a rebuild.

**Comment by hoppfrosch** [comment]
Does not work yet:
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "d:\\Usr\\programme\\nodejs\\node.exe" "C:\\Users\\jok\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "webpack" "-w"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

npm ERR! missing script: webpack
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     d:\Projects\AHK\_External\Gdip2\npm-debug.log
```

I'm a npm-noob ;-)

**Comment by tariqporter** [comment]
Please do a `git pull` again as `package.json` has been updated to run webpack with watch by default
```npm run webpack```

**Comment by hoppfrosch** [comment]
Thanks a lot - problem solved due your detailed instructions ...

**Comment by tariqporter** [comment]
Great! Hopefully others start using ahk-loader with webpack to build libraries that are more manageable as separate files

**Comment by hoppfrosch** [comment]
Have to look into all those node.js/webpack stuff .... ;-)
